export const OBLIQUE_STRATEGIES = [
  "Honor thy error as a hidden intention",
  "Look closely at the most embarrassing details and amplify them",
  "Use an old idea",
  "State the problem in words as clearly as possible",
  "Only one element of each kind",
  "What is the simplest solution?",
  "Turn it upside down",
  "Work at a different speed",
  "Ask your body",
  "Emphasize differences",
  "Discover the recipes you are using and abandon them",
  "Remove specifics and convert to ambiguities",
  "Disconnect from desire",
  "Breathe more deeply",
  "Make a sudden, destructive unpredictable action; incorporate",
  "Do the words need changing?",
  "Change instrument roles",
  "Accept advice",
  "Define an area as 'safe' and use it as an anchor",
  "Repetition is a form of change",
  "Go slowly all the way round the outside",
  "Take away the elements in order of apparent non-importance",
  "Don't avoid what is easy",
  "Decorate, decorate",
  "What are you really thinking about just now? Incorporate",
  "Look at the order in which you do things",
  "Destructive patterns",
  "Use filters",
  "It is quite possible to work alone",
  "Into the impossible",
  "Is the tuning appropriate?",
  "Courage!",
  "Always first steps",
  "Revaluation (a warm feeling)",
  "Faced with a choice, do both",
  "Give way to your worst impulse",
  "Make a blank valuable by putting it in an exquisite frame",
  "Slow preparation, fast execution",
  "Fill every beat with something",
  "List the qualities it has. List the qualities it lacks",
  "Is there something missing?",
  "Overtly resist change",
  "Do the dirty work",
  "Put in gridlock",
  "Allow an easement (an easement is the right to trespass or otherwise use another's land for a specified purpose)",
  "Listen to the quiet voice",
  "You don't have to be ashamed of using your own ideas",
  "Look at a very small object, look at its limit",
  "Retrace your steps",
  "Ask your pocket",
  "Destroy the most important thing",
  "Make it more simple",
  "Is it finished?",
  "What would your closest friend do?",
  "Use an unacceptable color",
  "Faced with a wall, build a window",
  "Subtract one digit from all values",
  "Look at the project through the eyes of an amateur",
  "Make a list of things you will not do under any circumstances",
  "Translate it into a different medium",
  "Focus on the gaps, not the solid objects",
  "Do something boring",
  "Invert the priority list",
  "Make a map of the mistakes",
  "Introduce a slow leak",
  "Let the text sleep for a night",
  "Only write in the margins",
  "Magnify the smallest sound",
  "Do not commit to the first draft",
  "Make the system fragile",
  "Let the crowd decide the first parameter",
  "Hide a secret code inside",
  "Build a bridge to an unrelated field",
  "Use only materials found within arm's reach",
  "What if the project failed? Make that the goal",
  "Simplify the transition points",
  "Slow down the intake of new information",
  "Change the rules of engagement mid-way",
  "Make it look like something else entirely",
  "Abandon the current canvas",
  "Do the opposite of what is expected",
  "Work with a constraint that makes you angry",
  "Find the quietest frequency",
  "Emphasize the seams and joints",
  "What is the background noise saying?",
  "Make the interface require two hands",
  "Remove the central feature",
  "Is it too comfortable?",
  "Describe it to a child",
  "Let it rust",
  "Make it float",
  "Reframe the target audience as a single person",
  "Trade a feature for a constraint",
  "Use only black, white, and a single neon color",
  "Multiply the scale by ten",
  "Divide the budget in half",
  "Change the language of operation",
  "Incorporate the weather outside",
  "Think of the project as a physical space",
  "Make the entry point hidden",
  "Make the exit point rewarding",
  "Introduce an element of deliberate friction",
  "Ask: What would a medieval guild do?",
  "Draw a circle around the main issue, then ignore the circle",
  "Use an element from a project you abandoned"
];

export const PHYSICAL_OBJECTS = [
  "dried leaves",
  "gold coins",
  "smooth stones",
  "rusty keys",
  "cotton string",
  "glass jars",
  "colored chalk",
  "wax candles",
  "wooden buttons",
  "folded paper",
  "seashells",
  "cork stoppers",
  "clay pots",
  "iron nails",
  "dried lavender",
  "copper wire",
  "linen scraps",
  "pinecones",
  "bamboo sticks",
  "pebbles",
  "old maps",
  "feather quill",
  "beeswax",
  "willow twigs",
  "hand-woven baskets",
  "old postcards",
  "brass bells",
  "wax paper",
  "glass marbles",
  "magnifying glass",
  "pocket watch",
  "burlap sacks",
  "rubber stamps",
  "lead pencils",
  "graph paper",
  "pressed flowers",
  "matchsticks",
  "wooden rulers",
  "copper pennies",
  "velvet ribbons",
  "tin cans",
  "seasalt crystals",
  "cinnamon sticks",
  "cotton fabric",
  "steel washers",
  "feather duster",
  "bamboo charcoal",
  "wool yarn",
  "leather scraps",
  "clay marbles",
  "seashell fragments",
  "parchment paper",
  "old dictionary",
  "inkwell",
  "typewriter keys",
  "driftwood",
  "porcelain shards",
  "vintage skeleton keys",
  "balsa wood",
  "magnets",
  "hemp rope",
  "cardboard tubes",
  "foil wrappers",
  "safety pins",
  "paperclips",
  "glass vials",
  "dried orange slices",
  "origami cranes",
  "spools of thread",
  "cigar boxes",
  "mirror fragments",
  "ceramic tiles",
  "wooden dowels",
  "wine corks",
  "chalkboard pieces"
];

export const SENSORY_DETAILS = [
  "a damp, mossy smell",
  "rough, weathered textures",
  "the sound of wind through pines",
  "flickering, warm candlelight",
  "a sharp, metallic chime",
  "the earthy scent of rain (petrichor)",
  "cool, running water",
  "the gritty feel of sand",
  "creaking old wood",
  "the faint aroma of woodsmoke",
  "a soft, brushed finish",
  "the low hum of a distant crowd",
  "sun-warmed leather",
  "the rustle of dry leaves",
  "polished, cold marble",
  "the smell of old paper and dust",
  "the crisp chill of morning air",
  "the scent of fresh cut grass",
  "a low, rhythmic tapping",
  "warm, textured wool",
  "the bright glare of neon signs",
  "the clean scent of peppermint",
  "a soft, velvety touch",
  "the smell of sea salt and ozone",
  "the crunch of dry gravel",
  "a gentle, cool breeze",
  "the taste of bitter chocolate",
  "the high-pitched buzz of a CRT screen",
  "the smell of roasted coffee beans",
  "the smooth glide of polished glass",
  "the crackle of static electricity",
  "the damp chill of a cellar",
  "warm, dry sand underfoot",
  "the scent of jasmine in the evening",
  "a soft, repetitive whisper",
  "the smell of new rain on dry asphalt",
  "the vibrant hue of sunset orange",
  "the feel of cold running stream water",
  "the scent of cedar wood",
  "the muffled echo of footsteps",
  "a faint, sweet honey aroma",
  "the sound of distant church bells",
  "rough, coarse sandpaper texture",
  "the smell of fresh pine needles",
  "the tickle of grass blades"
];

export const LOCATIONS = [
  "a bustling school fair",
  "a quiet corner of a public park",
  "a sleepy village square",
  "the steps of an old library",
  "a community garden plot",
  "a local farmers market",
  "beside a slow-moving river",
  "a flea market stall",
  "under a large weeping willow",
  "a dusty second-hand bookstore",
  "a neighborhood street corner",
  "the edge of a forest trail",
  "a local community hall",
  "a busy subway platform",
  "a quiet rooftop garden",
  "an old antique shop",
  "an airport terminal lounge",
  "a botanical conservatory",
  "a local community pool",
  "a cozy coffee shop corner",
  "a dim parking garage",
  "a neighborhood block party",
  "an empty beach at dusk",
  "a local thrift store",
  "a university lecture hall",
  "a public greenhouse",
  "a plant nursery",
  "a dock on a quiet lake",
  "a historic museum lobby",
  "a quiet church courtyard",
  "a virtual Discord server room",
  "a high-school basketball court",
  "a local post office lobby",
  "a busy street food alley",
  "a quiet harbor pier",
  "a weekend craft market",
  "a community workshop",
  "a local bakery porch",
  "a mountain trail rest stop",
  "a city train station waiting room"
];

export const ACTIONS = [
  "paint or dye them",
  "carve intricate patterns",
  "tie with organic twine",
  "melt or fuse together",
  "stamp with a custom emblem",
  "write short poems or words upon",
  "arrange in geometric grids",
  "press or flatten",
  "weave or braid",
  "polish until shiny",
  "bury and retrieve",
  "gift or trade secretly",
  "stack or balance",
  "stamp or print on them",
  "wrap in linen cloth",
  "seal with red wax",
  "etch a unique code",
  "soak in fragrant water",
  "glue into a mosaic",
  "engrave a name",
  "stitch with bright thread",
  "heat until they change color",
  "coat in clear varnish",
  "bind into a booklet",
  "dip in colored wax",
  "perfume with essential oils",
  "decorate with gold foil",
  "scrub until weathered",
  "arrange in concentric circles",
  "label with hand-written tags",
  "weave into a mesh",
  "sand until completely smooth",
  "group by color gradient",
  "drizzle with beeswax",
  "mount on small wooden boards",
  "drill a small hole through",
  "suspend from a string",
  "braid or knot tightly",
  "dust with mineral powders",
  "wrap with copper wire"
];
