name: Build and Push Chess Noise Filter Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'chess_noise_filter/**'
      - '.github/workflows/build-push-chess.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brad-is-love/chess-noise-filter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chess_noise_filter
          file: ./chess_noise_filter/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
